import type { NextPage } from "next";
import React from "react";
import Head from "next/head";
import { useFormik } from "formik";
import * as Yup from "yup";
import styles from "../styles/Home.module.css";
import { numVerify } from "../services/api/ValidateNumber";
import { Customer } from "../services/api/addCustomer";

import { Button, FormControl, TextField } from "@mui/material";

export type NumberProps = {
  carrier: string;
  country_code: string;
  country_name: string;
  country_prefix: string;
  international_format: string;
  line_type: string;
  local_format: string;
  location: string;
  number: string;
  valid: boolean;
};
export type CustomerInfoProps = {
  _id?: string;
  name?: string;
  address?: string;
  mobile?: string | null;
  countryCode?: string;
  countryName?: string;
};
const Home: NextPage = () => {
  const [customerInfo, setCustomerInfo] = React.useState<CustomerInfoProps>();
  const [number, setNumber] = React.useState<NumberProps>();
  const initialValues: CustomerInfoProps = {
    name: "",
    address: "",
    mobile: "",
    countryCode: "",
    countryName: "",
  };
  const validationSchema = () =>
    Yup.object({
      name: Yup.string().required("Required"),
      address: Yup.string().required("Required"),
      mobile: Yup.string().required("Required"),
    });
  const onSubmit = () => {
    numVerify
      .ValidateNumber(formik.values.mobile!)
      .then((res) => {
        if (res?.valid) {
          Customer.addCustomer({
            name: formik.values.name,
            address: formik.values.address,
            mobile: formik.values.mobile,
            countryCode: res?.country_prefix,
            countryName: res?.country_name,
          })
            .then((res) => alert(`Customer added successfuly`))
            .catch((res) => alert(`Customer asertion failed`));
        } else {
          alert(`Phone Number does not match country format `);
        }
      })
      .catch((error) => () => console.log(error));
  };

  const formik = useFormik({
    initialValues,
    validationSchema,
    onSubmit,
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={formik.handleSubmit}>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              flexDirection: "column",
            }}
          >
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
              }}
            >
              <FormControl>
                <TextField
                  label={"Name"}
                  type="text"
                  name="name"
                  onBlur={formik.handleBlur}
                  onChange={formik.handleChange}
                  value={formik.values.name}
                />
                {formik.errors.name && formik.touched.name ? (
                  // eslint-disable-next-line react/jsx-indent
                  <div style={{ width: "100%", color: "red" }}>
                    {formik.errors.name}{" "}
                  </div>
                ) : null}
              </FormControl>

              <br />
              <FormControl>
                <TextField
                  label={"Address"}
                  type="text"
                  name="address"
                  onBlur={formik.handleBlur}
                  onChange={formik.handleChange}
                  value={formik.values.address}
                />
                {formik.touched.address && formik.errors.address ? (
                  // eslint-disable-next-line react/jsx-indent
                  <div style={{ width: "100%", color: "red" }} color="red">
                    {formik.errors.address}{" "}
                  </div>
                ) : null}
              </FormControl>
              <br />
              <FormControl>
                <TextField
                  label={"Phone Number"}
                  type="number"
                  name="mobile"
                  onBlur={formik.handleBlur}
                  onChange={formik.handleChange}
                  value={formik.values.mobile}
                />
                {formik.errors.mobile && formik.touched.mobile ? (
                  // eslint-disable-next-line react/jsx-indent
                  <div style={{ width: "100", color: "red" }}>
                    {formik.errors.mobile}{" "}
                  </div>
                ) : null}
              </FormControl>
              <br />
              <Button variant="contained" type="submit">
                Add Customer
              </Button>
            </div>
            <h2>{number?.country_name}</h2>
          </div>
        </form>
      </main>

      {/* <footer className={styles.footer}>
        <p>Powered by ali berro </p>
      </footer> */}
    </div>
  );
};

export default Home;
